# API definition
# Warning: Enabling API will expose Traefik's configuration.
# It is not recommended in production,
# unless secured by authentication and authorizations

global:
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: sedish-haitiorg_sedish

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: INFO
  format: common


